# Generated by Django 5.2.8 on 2025-11-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='pago',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_date',
            field=models.DateField(default='2020-10-20', verbose_name='Data de Pagamento'),
            preserve_default=False,
        ),
    ]
