# Generated by Django 5.2.8 on 2025-11-16 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0004_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('Q', 'Quitado'), ('V', 'Vencido'), ('C', 'Cancelado')], default=django.utils.timezone.now, max_length=2, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida')], max_length=2, verbose_name='Tipo'),
        ),
    ]
