# Generated by Django 5.2.5 on 2025-10-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='situation',
            new_name='status',
        ),
    ]
