# Generated by Django 5.2.5 on 2025-10-26 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_rename_situation_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(max_length=100)),
                ('fantasy_name', models.CharField(max_length=100)),
                ('responsible', models.CharField(blank=True, max_length=100, null=True)),
                ('type_person', models.CharField(max_length=2)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg_ie', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('cell_phone', models.CharField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, null=True)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Assinatura', 'verbose_name_plural': 'Assinaturas'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateField(blank=True, null=True, verbose_name='data de cancelamento'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de criacao'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_frequency',
            field=models.CharField(choices=[('M', 'Mensal'), ('T', 'Trimestral'), ('A', 'Anual')], max_length=20, verbose_name='Frequencia de pagamento'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('P', 'PIX'), ('B', 'Boleto')], max_length=20, verbose_name='Metodo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='renewal_day',
            field=models.IntegerField(verbose_name='Dia de renovação'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('C', 'Cancelado')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('I', 'Individual'), ('F', 'Familiar'), ('E', 'Estudante')], max_length=20, verbose_name='Tipo de Assinatura'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='data de atualizacao'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
