# Generated by Django 5.2.5 on 2025-10-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_supplier_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='supplier',
            field=models.ForeignKey(default=1, limit_choices_to={'situation': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='registrations.supplier'),
            preserve_default=False,
        ),
    ]
