# Generated by Django 5.2.5 on 2025-11-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_bankaccount_card_alter_subscription_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='situation',
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('CR', 'Crédito'), ('DB', 'Débito'), ('PP', 'Pré-pago')], max_length=2),
        ),
    ]
