# Generated by Django 5.2.5 on 2025-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_remove_card_situation_card_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='notes',
        ),
        migrations.AddField(
            model_name='card',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='card',
            name='billing_day',
            field=models.PositiveSmallIntegerField(verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=50, verbose_name='Nome do cartão'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, verbose_name='Número do cartão'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('CR', 'Crédito'), ('DB', 'Débito'), ('PP', 'Pré-pago')], max_length=2, verbose_name='Tipo de Cartão'),
        ),
        migrations.AlterField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de credito'),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_day',
            field=models.PositiveSmallIntegerField(verbose_name='Renovação'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('V', 'Vencido'), ('I', 'Inativo')], default='A', max_length=2, verbose_name='Status'),
        ),
    ]
