# Generated by Django 5.2.5 on 2025-11-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_remove_card_notes_card_observation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='situation',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(default=1, max_length=2, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=30, verbose_name='Número da conta'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(max_length=3, verbose_name='Tipo de conta'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='agency_number',
            field=models.CharField(max_length=20, verbose_name='Número do agencia'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Nome do banco'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
