# Generated by Django 5.2.5 on 2025-11-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_alter_card_options_remove_bankaccount_situation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conta Bancaria', 'verbose_name_plural': 'Contas Bancaria'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('INV', 'Investimento')], max_length=3, verbose_name='Tipo de conta'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real Brasileiro'), ('USD', 'Dólar Americano')], default='BRL', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=2, verbose_name='status'),
        ),
    ]
