# Generated by Django 5.2.5 on 2025-11-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
