# Generated by Django 5.2.8 on 2025-11-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_alter_supplier_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='supplier',
        ),
    ]
